
@PROXY_URL=https://rlp-proxy.herokuapp.com/v2?url=

###
GET {{PROXY_URL}}https://store.steampowered.com/app/3830/Psychonauts/

###
POST http://localhost:3000/api/addBookmark
Content-Type: application/json

{

}

###
POST http://localhost:3000/api/getBookmarks
Content-Type: application/json

{

}

###
POST http://localhost:3000/api/updateBookmark
Content-Type: application/json

{
   "id": "626ffbd3fc2ba948f768eb8b",
   "bookmark": {
      "type": "text"
   }
}


###
GET https://store.steampowered.com/search/suggest?term=star&cc=RO