
@PROXY_URL=https://rlp-proxy.herokuapp.com/v2?url=
@HOST_URL=http://localhost:8080

###
GET {{PROXY_URL}}https://store.steampowered.com/app/3830/Psychonauts/

###
POST {{HOST_URL}}/api/addBookmark
Content-Type: application/json

{

}

###
POST {{HOST_URL}}/api/getBookmarks
Content-Type: application/json

{}

###
POST {{HOST_URL}}/api/updateBookmark
Content-Type: application/json

{
   "id": "626ffbd3fc2ba948f768eb8b",
   "bookmark": {
      "type": "text"
   }
}


###
GET https://store.steampowered.com/search/suggest?term=starve&cc=RO

###
GET https://store.steampowered.com/api/appdetails?appids=892970&cc=us

###
POST {{HOST_URL}}/api/getMetadataCandidates
Content-Type: application/json

{
   "type": "game",
   "title": "Valheim"
}

###
GET https://isbnsearch.org/search?s=Designing+Data-intensive+Applications

###
GET https://www.amazon.com/dp/1443321